title    ORBIT-OS 1.0 (x86_64, UEFI) - basic mode
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% efi_no_storage_paranoia systemd.unit=multi-user.target systemd.firstboot=no copytoram=n
