#
# ORBIT-OS 1.0 - pacman configuration
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
ParallelDownloads = 15
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

#
# REPOSITORIES
#

[orbit-repo]
SigLevel = Optional TrustAll
Server = file:///home/chris/orbit-repo

[core]
SigLevel = PackageRequired
Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch
Server = https://mirror.leaseweb.net/archlinux/$repo/os/$arch
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch

[extra]
SigLevel = PackageRequired
Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch
Server = https://mirror.leaseweb.net/archlinux/$repo/os/$arch
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch

[multilib]
SigLevel = PackageRequired
Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch
Server = https://mirror.leaseweb.net/archlinux/$repo/os/$arch
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
