# SPDX-License-Identifier: CC0-1.0
---
dontChroot: false
timeout: 999

script:
    - "-rm ${ROOT}/etc/sudoers.d/g_wheel"
    - "-rm -r ${ROOT}/etc/systemd/system/getty@tty1.service.d"
    - "-rm -r ${ROOT}/etc/systemd/system/multi-user.target.wants/pacman-init.service"
    - "-rm -r ${ROOT}/etc/systemd/system/pacman-init.service"
    - "-rm ${ROOT}/etc/systemd/system/etc-pacman.d-gnupg.mount"
    - "-rm ${ROOT}/root/.automated_script.sh"
    - "-rm ${ROOT}/root/.zlogin"
    - "-rm ${ROOT}/etc/polkit-1/rules.d/49-nopasswd_global.rules"
    - "-rm ${ROOT}/etc/polkit-1/rules.d/49-nopasswd-calamares.rules"
    - "-rm -f ${ROOT}/etc/sddm.conf.d/autologin.conf"
    - "-rm -f ${ROOT}/home/${USER}/Desktop/orbit-install.desktop"
    - "-rm -f ${ROOT}/usr/share/applications/orbit-install.desktop"
    - "-rm -f ${ROOT}/home/${USER}/.config/powermanagementprofilesrc"
    - "systemctl enable NetworkManager"
    - "systemctl enable bluetooth"
    - "systemctl enable power-profiles-daemon"
    - "mkdir -p ${ROOT}/home/${USER}/.config/systemd/user/plasma-powerdevil.service.d"
    - "printf '[Service]\\nEnvironment=\"POWERDEVIL_NO_DDCUTIL=1\"\\n' > ${ROOT}/home/${USER}/.config/systemd/user/plasma-powerdevil.service.d/override.conf"
    - "chown -R 1000:1000 ${ROOT}/home/${USER}/.config"
