# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration file for Calamares
#
---
modules-search: [ local ]

instances:
- id:       wipe
  module:   shellprocess
  config:   shellprocess-wipe.conf
- id:       before
  module:   shellprocess
  config:   shellprocess-before.conf
- id:       prefix
  module:   shellprocess
  config:   shellprocess-prefix.conf
- id:       locateimg
  module:   shellprocess
  config:   shellprocess-locateimg.conf
- id:       grubinstall
  module:   shellprocess
  config:   shellprocess-grubinstall.conf
- id:       grubfix
  module:   shellprocess
  config:   shellprocess-grubfix.conf
- id:       final
  module:   shellprocess
  config:   shellprocess-final.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - shellprocess@wipe
  - partition
  - users
  - summary
- exec:
  - shellprocess@wipe
  - partition
  - mount
  - shellprocess@locateimg
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - shellprocess@prefix
  - initcpiocfg
  - initcpio
  - removeuser
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - shellprocess@before
  - grubcfg
  - shellprocess@grubinstall
  - shellprocess@grubfix
  - shellprocess@final
  - preservefiles
  - umount
- show:
  - finished

branding: orbit

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: false

quit-at-end: false
